language: ruby
rvm:
- 2.1

before_script:
- git config --global user.name 'Apisense team'
- git config --global user.email 'apisense@gmail.com'

script: ./scripts/cibuild

branches:
  only:
  - master

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../_site/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages