language: ruby
rvm:
- 2.1

branches:
  only:
  - master

before_script:
- openssl aes-256-cbc -K $encrypted_afa5917f0033_key -iv $encrypted_afa5917f0033_iv -in .travis_rsa.enc -out .travis_rsa -d
- git config --global user.name 'Travis CI'
- git config --global user.email 'apisense@gmail.com'

script: ./scripts/cibuild

