# Site settings
title: APISENSE® Documentation

email: contact@apisense.io
description: >
  APISENSE® leverages data collected from a crowd of mobile devices.
  Observe and innovate using users' feedback, in real time!

baseurl: ""

defaultVersion: 1.9.0

url: http://apisense.github.io/docs/
#url: http://127.0.0.1:4000/ # url: http://docs.apisense.io/

twitter_username: APISENSE
github_username:  APISENSE

# Build settings
markdown: kramdown
highlighter: pygments #rouge

exclude: [vendor]
