# Site settings
title: APISENSE® Documentation
email: contact@apisense.com
description: > # this means to ignore newlines until "baseurl:"
  Official APISENSE® documentation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://193.51.236.172:4000/" # the base hostname & protocol for your site
twitter_username: APISENSE
github_username:  APISENSE

# Build settings
markdown: kramdown
highlighter: rouge